### ISSUE TITLE
Plugin install issue and getting error on package com.rewire.app

### ISSUE THREAD

**Issue by maniveltvl** [rewireltd1/cordova-plugin-onfido#1]
Hi, Team
I have couple of issues.

1. If I try to install this plugin, i am getting the below error
D:\Project>**cordova plugin add https://github.com/rewireltd1/cordova-onfido-plugin**
Failed to fetch plugin https://github.com/rewireltd1/cordova-onfido-plugin via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module

And I tried the below way

D:\Project>**cordova plugin add cordova-onfido-plugin**
cmd: Command failed with exit code 1 Error output:
npm ERR! code E404
npm ERR! 404 'cordova-onfido-plugin' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! 404
npm ERR! 404  'cordova-onfido-plugin@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

Finally I worked by the below command 

D:\Project>**cordova plugin add https://github.com/rewireltd1/cordova-onfido-plugin.git**
Installing "onfido-cordova-plugin" for android
Subproject Path: CordovaLib
Subproject Path: app
Adding onfido-cordova-plugin to package.json
Saved plugin info for "onfido-cordova-plugin" to config.xml

2. After Install this plugin, I have reinstall my Android platform and i have built. While building my Android, I am getting the below error.

platforms\android\app\src\main\java\com\plugin\onfido\OnFidoBridge.java:19: error: **package com.rewire.app does not exist
import com.rewire.app.R;**

Can you please resolve this issue?

**Comment by RoyRewire** [comment]
This issue has been fixed in our latest update. Please try again
