### ISSUE TITLE
Is an official plugin?

### ISSUE THREAD

**Issue by adriansaenz** [rewireltd1/cordova-plugin-onfido#2]
Hello, i have the doubt that this plugin is an official plugin or just one that you did by yourself. Let me know as i have to know if it is now updated and it will be maintained in the future.

Thanks in advance.

**Comment by alonp99** [comment]
Hi Adrian, This is not an official plugin, as we understood from onfido team - they will not put efforts into Cordova plugins.
This plugin is maintained and used in production, we look for partners to join force with us, make it better and stay inline with Onfido SDK updates.
