### ISSUE TITLE
No pod version specified

### ISSUE THREAD

**Issue by adriansaenz** [rewireltd1/cordova-plugin-onfido#3]
Hi,

i've just noticed that any version is specified in spec attribute from plugin.xml.
 
<framework src="Onfido" type="podspec" spec=""/>

Means that it has to take the last version of sdk? In this case the ionic build is failling because there is an interface that is not recognize.
Any suggestion?

**Comment by alonp99** [comment]
make sure you are running the latest version (1.0.5)
if the issue persists, post here the logs and we will help you

**Comment by adriansaenz** [comment]
I've managed to make a build but once the app is started the following error is displayed in xcode output console:
dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
 Referenced from: /private/var/containers/Bundle/Application/D04AF219-1E94-476D-BB19-E8DDBA48A32C/NAME.app/Frameworks/Onfido.framework/Onfido
 Reason: image not found

Any idea?

**Comment by adriansaenz** [comment]
Changing in pod framework 'Onfido' by 'Onfido-Release' this issue is solved.
